name: Docker Matrix Strategy
on: push

jobs:
  docker-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        image: [hello-world, busybox]
        include:
          - os: ubuntu-latest
            image: alpine
        exclude:
          - os: windows-latest
            image: busybox

    runs-on: ${{ matrix.os }}
    steps:
      - name: Run Docker Container
        run: |
          echo "Running on ${{ matrix.os }} with Docker image: ${{ matrix.image }}"
          docker run ${{ matrix.image }}
