name: Matrix Strategy
on: push

jobs:
  test-matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Show OS and Python version
        run: |
          echo "Running on OS: ${{ matrix.os }}"

      - name: Verify Python Version
        run: python --version
