name: Docker Matrix Build
on: push

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        image: [hello-world, busybox]
        include:
          - os: ubuntu-latest
            image: "alpine"
        exclude:
          - os: windows-latest
            image: "alpine"  # Exclude Alpine on Windows

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install Docker (Windows)
        if: runner.os == 'Windows'
        run: choco install docker-cli

      - name: Install Docker (macOS)
        if: runner.os == 'macOS'
        run: brew install docker

      - name: Run Docker Container
        run: |
          echo "Runs on ${{ matrix.os }}"
          docker run ${{ matrix.image }}
