name: Docker Matrix Build
on: push

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        image: [hello-world, alpine]
        include:
          - os: ubuntu-latest
            image: "alpine"
        exclude:
          - os: windows-latest
            image: "alpine"  # Exclude Alpine on Windows

    runs-on: ${{ matrix.os }}

    steps:
      - name: Run Docker Container
        run: |
         echo "Runs on ${{ matrix.os }}"
         docker run ${{ matrix.image }}
