name: Matrix Strategy
on: push

jobs:
  test-matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8, 3.10]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Show OS and Python version
        run: |
          echo "Running on OS: ${{ matrix.os }}"
          echo "Using Python version: ${{ matrix.python-version }}"

      - name: Verify Python Version
        run: python --version
