name: Matrix Include and Exclude
on: push

jobs:
  test-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8, 3.11]
        include:
          - os: ubuntu-latest
            python-version: 3.12
        exclude:
          - os: windows-latest
            python-version: 3.8

    steps:
      - name: Display matrix combination
        run: |
          echo "OS: ${{ matrix.os }}, Python: ${{ matrix.python-version }}"
