name: Upload and Download Artifacts
on: push

jobs:
  upload-file:
    runs-on: ubuntu-latest
    steps:
      - name: Create a file
        run: echo "This is a test file" > hello.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-file
          path: hello.txt

  download-file:
    runs-on: ubuntu-latest
    needs: upload-file
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: test-file

      - name: Display file contents
        run: cat hello.txt
